# Generated by Django 5.0.6 on 2024-06-14 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Theblog', '0003_alter_post_title_alter_post_title_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=25000),
        ),
    ]
