# Generated by Django 5.0.6 on 2024-06-17 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Theblog', '0005_profile_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone_number',
        ),
    ]
