# Generated by Django 5.0.6 on 2024-06-17 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Theblog', '0007_follower'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follower',
        ),
    ]
